# NumPy Essentials for Data Science 


In [1]:
import numpy as np


In [2]:


array=np.array([1,2,3])
print(array)

array1=np.array([[1,2,3,4],[5,6,7,8]])
print(array1*3)

[1 2 3]
[[ 3  6  9 12]
 [15 18 21 24]]


### creating array from list

### creating arrray from scratch (using zeros array )

In [3]:
array_zeros=np.zeros((4,5))
print("array_zeros :\n",array_zeros)

array_zeros :
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### creating array using Ones 

In [4]:
arrray_ones=np.ones((3,4))
print("ones array : \n",arrray_ones)

ones array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
arrray_const=np.array([[1,2,3],[5,6,7],[8,8,1]])
print(arrray_const)

[[1 2 3]
 [5 6 7]
 [8 8 1]]


### constant array making using full method


In [6]:
array_full=np.full((3,4),7 ) # 7 is a prameter for constant value
print("const array example :\n",array_full)

const array example :
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


### array making random values

In [7]:
arrray_random=np.random.random((3,2))  
print("random array :\n",arrray_random)

random array :
 [[0.82908417 0.82624771]
 [0.80038198 0.0028435 ]
 [0.68425012 0.1201266 ]]


### sequence  to print array (starting_number , ending_number , step)
###### (0,10,2)  here 0 is starting number   , 10 is a ending number (but it will end at 9 beacuse python is a implicitly exclusive that's why ending number-1)  and 2 is a step between to numbers 

In [8]:
import numpy as np
array_sequence=np.arange(0,16,2)
print("sequence array \n ",array_sequence)

sequence array 
  [ 0  2  4  6  8 10 12 14]


# Vector , Matrix , Tensor in numpy

In [9]:
# #example of vector
# vector=np.array([1,2,3,4])
# print("vector example \n",vector)


# #example of matrix
# matrix=np.array([[1,2,3,4],[5,6,7,8]])
# print("matrix example \n ", matrix)



#exaple of tensor
tensor=np.array([[[1,2,3],[4,5,6]],
                 [[5,6,7],[7,8,9]]])
print("tensor example \n ",tensor)


tensor example 
  [[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [7 8 9]]]


# properties of Arrays

In [10]:
import numpy as np
array_prop=np.array([[1,3,5,6],
                     [7,8,9,0],
                     [1,8,4,7]])


print("shape",array_prop.shape) # to find the shape of an array 
print("dimension of array :",array_prop.ndim)  # to find the dimension of an array 
print("size of an array :",array_prop.size) # to find the size of an array 
print("data type of an array :",array_prop.dtype) # to find the datatype of an array 


shape (3, 4)
dimension of array : 2
size of an array : 12
data type of an array : int64


### reshaping the array

In [11]:
arr=np.arange(12)
print(" arrray before reshape \n",arr)

reshape=arr.reshape((4,3))
print("array using reshape method \n",reshape)

 arrray before reshape 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
array using reshape method 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### falting the reshape array 


In [12]:
array = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print("array before floating \n",array)

array_flat=array.flatten()
print("array after flat \n",array_flat)

array before floating 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
array after flat 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


### raveled array (returns view , instead of copy)

In [13]:
arr=np.array([[10,22,33,44],[11,22,33,44]])
print("array before raveled \n",arr)

ravel_array=arr.ravel()
print( "array after ravel \n",ravel_array)

array before raveled 
 [[10 22 33 44]
 [11 22 33 44]]
array after ravel 
 [10 22 33 44 11 22 33 44]


### Tanspose the array


In [14]:
arr=np.array([[1,2,1,3,2,3],[4,4,4,5,6,1]])
print("array before Transpose\n",arr)
transpose_arr=arr.T
print("array after transpose \n",transpose_arr)

array before Transpose
 [[1 2 1 3 2 3]
 [4 4 4 5 6 1]]
array after transpose 
 [[1 4]
 [2 4]
 [1 4]
 [3 5]
 [2 6]
 [3 1]]


# Learning numpy 

### basic slicing in  1D array 

In [15]:
arr_slice=np.array([1,2,3,4,5,6,7,8,9,0])
print("basic slicing of an  array :",arr_slice[1:7])


##negative basic slicing
arr_negative_slice=([2,3,4,5,6,7,8])
print("basic negative slicing of an array :",arr_negative_slice[-4])


## slicing with step (we need to give steps also )
arr_step_slice=([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("slicing the array with steps : ",arr_step_slice[3:12:3]) # 3 is the value of step 


basic slicing of an  array : [2 3 4 5 6 7]
basic negative slicing of an array : 5
slicing the array with steps :  [4, 7, 10]


### basics of slicing in 2D array

In [16]:
arr_2D_slice=np.array([[3,6,9],
                       [1,3,5],
                       [2,4,6],
                       [4,8,12],
                       [1,0,1]])


print("basic slicing of an 2D array :",arr_2D_slice[3,2])  # 3 is the row number 3 rd row 2nd index 
print("basic slicing of an 2D array :",arr_2D_slice[4,0])  # 4 is the row number 4 rd row 1nd index 


basic slicing of an 2D array : 12
basic slicing of an 2D array : 1


#### slicing of array for with targeting entire Row 

In [17]:
arrRowWhole=np.array([[2,4,4,5],
                    [4,9,7,2],
                    [1,4,5,1],
                    [4,5,2,4],
                    [9,9,7,7],
                    [9,1,4,5]])

print("targeting entire row of an array :",arrRowWhole[3])  # targeting entire  3rd row 
print("targeting entire row of an array :",arrRowWhole[0])  # targeting entire  0th row 


targeting entire row of an array : [4 5 2 4]
targeting entire row of an array : [2 4 4 5]


### slicing of an array with targeting entire columns

In [18]:
arrColumnWhole=np.array([[4,9,7,2],
                         [9,1,4,5],
                         [4,5,2,4],
                         [2,4,4,5]])
print("targeting entire Column of an array :",arrColumnWhole[:,3])  # : means row and 3 for all rows 3rd index
print("targeting entire Column of an array :",arrColumnWhole[:,0])  # : means row and 3 for all rows 3rd index

print("targeting entire Column of an array :",arrColumnWhole[2,1])  # 2 for row and 1  is the column of the 2nd row

targeting entire Column of an array : [2 5 4 5]
targeting entire Column of an array : [4 9 4 2]
targeting entire Column of an array : 5


## Sorting  1D array

In [19]:
sortingArray=np.array([1,11,3,2,33,22,12,22,111,32,0,8,6,4,2])

print("sorting the array :",np.sort(sortingArray))   # np.sort is used to sort the array

sorting the array : [  0   1   2   2   3   4   6   8  11  12  22  22  32  33 111]


## Sorting 2d array

In [20]:
arrSorting2D=np.array([[4,9,7,2],
                         [9,1,4,5],
                         [4,15,2,4],
                         [2,4,4,5]])

print("sorting the 2D by columns  with axis  0: \n",np.sort(arrSorting2D,axis=0)) # axis 0 is widly used

print("sorting the 2D by columns  with axis 1:\n",np.sort(arrSorting2D,axis=1))

sorting the 2D by columns  with axis  0: 
 [[ 2  1  2  2]
 [ 4  4  4  4]
 [ 4  9  4  5]
 [ 9 15  7  5]]
sorting the 2D by columns  with axis 1:
 [[ 2  4  7  9]
 [ 1  4  5  9]
 [ 2  4  4 15]
 [ 2  4  4  5]]


## Filtering  the array


In [21]:
import numpy as np
array_filter=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14 ])
evenNumber=array_filter[array_filter %2==0]
print("even numbers of an array :",evenNumber)

even numbers of an array : [ 2  4  6  8 10 12 14]


## Filtering the array with mask 

In [22]:
array=np.array([10,20,30,40,50,60,70,80,90,100,110,112,130,140,150])
mask_array=array >60
print("numbers that greater than 60 :",array[mask_array])
maskArray2=array<=100
print("numbers that are smaller than and equal to 100 :",array[maskArray2])

numbers that greater than 60 : [ 70  80  90 100 110 112 130 140 150]
numbers that are smaller than and equal to 100 : [ 10  20  30  40  50  60  70  80  90 100]


## Fancy indexing vs np.where()

In [23]:
# finding the index of the array 
array=np.array([1,23,43,54,67,55,77,43,53,56,55,42,4,78,998,8,7,66,90])
index=[0,3,6,9,11,13,15]
print("indexs of the array",array[index])


# using where in the array
arr=np.array([0,3,6,9,11,13,15,1 ,54 ,77, 56, 42, 78,  8])
whereArr=np.where(arr>50)
print("result using where in the array :",arr[whereArr])

indexs of the array [ 1 54 77 56 42 78  8]
result using where in the array : [54 77 56 78]


##  Adding and Removing Data

In [24]:
## merging two array using  concatenate
import numpy as np
arr1=np.array([10,290,300,40,50,690,700,980,990])
arr2=np.array([100,200,300,400,500,600,700,800,900])

arrMerge=np.concatenate((arr1,arr2))
print(arrMerge)


[ 10 290 300  40  50 690 700 980 990 100 200 300 400 500 600 700 800 900]


In [25]:
import numpy as np
array=np.array([10,11,2,3,44,55,45])
arrMean=np.mean(array)
print("mean :",arrMean)
arrMean=np.median(array)
print("median :",arrMean)
arrMean=np.std(array)
print("standerd deviation  :",arrMean)






mean : 24.285714285714285
median : 11.0
standerd deviation  : 21.015057769638048
